### ISSUE TITLE
TypeScript compile error `TS1479` even if you import `option-t/lib/*` or `option-t/cjs/*` in a project set `moduleResolution=node16` & `type=commonjs`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#1515]
### Step 0

Set up a project containing these files.

#### /package.json

```json
{
    "type": "commonjs",
    "scripts": {
        "build": "tsc"
    },
  "devDependencies": {
    "typescript": "^4.9.4"
  }
}
```

#### /src/bar.ts

```ts
import {} from `option-t/lib/Nullable/Nullable`;
```

#### tsconfig.json

```json5
{
    "moduleResolution": "Node16",
}
```

### Step 1

Run `npm run build`

## Actual Result

tsc show this error

> error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("option-t/lib/Nullable/Nullable")' call instead.
>  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

**Comment by tetsuharuohzeki** [comment]
This bug is caused since https://github.com/karen-irc/option-t/pull/1419/commits/bf6a2374c0e0db95702d4c69c87e49704f46fe59 ([v32.6.5](https://github.com/karen-irc/option-t/releases/tag/v32.6.5))

**Comment by tetsuharuohzeki** [comment]
#1522 reopen this....
